open-webrtc-toolkit/owt-client-native

talk/owt/BUILD.gn, talk/owt/sdk/conference/objc/ConferenceClientObserverObjcImpl.mm, talk/owt/sdk/conference/objc/OWTConferenceParticipant+Private.h, talk/owt/sdk/conference/objc/OWTConferenceParticipant.mm, talk/owt/sdk/conference/objc/ParticipantObserverObjcImpl.h, talk/owt/sdk/conference/objc/ParticipantObserverObjcImpl.mm, talk/owt/sdk/include/objc/OWT/OWTConferenceParticipant.h
=> Implement participant events

talk/owt/sdk/conference/conferenceclient.cc, talk/owt/sdk/conference/objc/OWTRemoteMixedStream.mm, talk/owt/sdk/conference/objc/RemoteMixedStreamObserverObjcImpl.h, talk/owt/sdk/conference/objc/RemoteMixedStreamObserverObjcImpl.mm, talk/owt/sdk/conference/remotemixedstream.cc, talk/owt/sdk/include/cpp/owt/conference/remotemixedstream.h, talk/owt/sdk/include/objc/OWT/OWTRemoteMixedStream.h
ActiveInput notification on the mixed stream to upperlayer
=> IOS: ActiveInput notification to upper layer

jenkins/android.jenkinsfile
Reverts open-webrtc-toolkit/owt-client-native#137
=> Revert "Run android native ci build with docker"

talk/owt/sdk/conference/conferencesocketsignalingchannel.cc
https://github.com/open-webrtc-toolkit/owt-server/blob/e79ff2519bfb096548a8ffad3b549a570d49175f/source/portal/socketIOServer.js#L243-L254
https://github.com/open-webrtc-toolkit/owt-server/blob/e79ff2519bfb096548a8ffad3b549a570d49175f/source/portal/socketIOServer.js#L128-L130
=> Returned status maybe "ok" from newer version of SocketIOServer

scripts/prepare_dev.py, talk/owt/BUILD.gn, talk/owt/patches/0009-Export-WebRTC-symbols-on-iOS.patch
=> Export WebRTC symbols on iOS.

talk/owt/sdk/conference/conferencepublication.cc, talk/owt/sdk/include/cpp/owt/conference/conferencepublication.h
=> Implemented conference publication stop during stream remove

talk/owt/sdk/base/win/msdkvideoencoder.cc
=> Fix Windows client crash on shared application window resizing.

talk/owt/sdk/base/objc/OWTMediaFormat.mm, talk/owt/sdk/base/objc/OWTRemoteStream.mm, talk/owt/sdk/base/stream.cc, talk/owt/sdk/conference/conferenceclient.cc, talk/owt/sdk/conference/conferencepeerconnectionchannel.cc, talk/owt/sdk/conference/remotemixedstream.cc, talk/owt/sdk/include/cpp/owt/base/options.h, talk/owt/sdk/include/cpp/owt/base/stream.h, talk/owt/sdk/include/cpp/owt/conference/remotemixedstream.h, talk/owt/sdk/include/objc/OWT/OWTMediaFormat.h, talk/owt/sdk/include/objc/OWT/OWTRemoteStream.h
It is aligned with other SDKs. This change also fixes #221.
=> Update the definition of PublicationSettings.

talk/owt/sdk/base/peerconnectionchannel.cc, talk/owt/sdk/base/peerconnectionchannel.h, talk/owt/sdk/conference/conferencepeerconnectionchannel.cc
=> Set transceiver's direction instead of OfferToReceiverAudio/OfferToReceiverVideo.

talk/owt/sdk/base/peerconnectionchannel.cc, talk/owt/sdk/base/peerconnectionchannel.h, talk/owt/sdk/conference/conferencepeerconnectionchannel.cc, talk/owt/sdk/p2p/p2ppeerconnectionchannel.cc
=> Replace internal add stream with add transceiver.

talk/owt/sdk/p2p/p2pclient.cc
=> Don't try to acquire pc_channels_mutex_ twice.

talk/owt/sdk/base/desktopcapturer.h, talk/owt/sdk/base/functionalobserver.h, talk/owt/sdk/conference/conferenceclient.cc, talk/owt/sdk/conference/conferencepeerconnectionchannel.h, talk/owt/sdk/include/cpp/owt/base/connectionstats.h, talk/owt/sdk/include/cpp/owt/p2p/p2pclient.h, talk/owt/sdk/include/objc/OWT/OWTP2PClient.h, talk/owt/sdk/p2p/p2ppeerconnectionchannel.h
Signed-off-by: Geoff Gustafson <geoff@linux.intel.com>
=> Correct some overreplacement of OWT string

DEPS, scripts/prepare_dev.py, talk/owt/BUILD.gn, talk/owt/patches/0004-Remove-webrtc_overrides.patch, talk/owt/sdk/base/customizedaudiodevicemodule.cc
This enables Windows/iOS SDK build on M79.
=> Enable Windows SDK build on M79.

scripts/build-win.py
This replace shell=True with shell=False and also checks ssl_root and msdk_root path.
=> Fix vulnerabilities reported by checkMax

README.md
=> Fix the link to prerequisite software.

DEPS, scripts/build-win.py, scripts/prepare_dev.py, talk/owt/patches/0001-Use-OpenSSL-for-usrsctp.patch, talk/owt/patches/0002-Use-OpenSSL-for-libsrtp.patch, talk/owt/patches/0004-Remove-webrtc_overrides.patch, talk/owt/patches/0007-Fix-examples-path-error.patch, talk/owt/patches/0013-Remove-unused-gni-for-av1-build.patch, talk/owt/patches/0014-Fix-missing-ffmpeg-configure-item-for-msvc-build.patch, talk/owt/sdk/base/cameravideocapturer.cc, talk/owt/sdk/base/functionalobserver.cc, talk/owt/sdk/base/functionalobserver.h, talk/owt/sdk/base/peerconnectionchannel.cc, talk/owt/sdk/base/peerconnectiondependencyfactory.cc
=> Rebase webrtc to M83

DEPS, scripts/build-win.py, scripts/prepare_dev.py, talk/owt/patches/0001-Use-OpenSSL-for-usrsctp.patch, talk/owt/patches/0002-Use-OpenSSL-for-libsrtp.patch, talk/owt/patches/0004-Remove-webrtc_overrides.patch, talk/owt/patches/0007-Fix-examples-path-error.patch, talk/owt/patches/0013-Remove-unused-gni-for-av1-build.patch, talk/owt/patches/0014-Fix-missing-ffmpeg-configure-item-for-msvc-build.patch, talk/owt/sdk/base/cameravideocapturer.cc, talk/owt/sdk/base/functionalobserver.cc, talk/owt/sdk/base/functionalobserver.h, talk/owt/sdk/base/peerconnectionchannel.cc, talk/owt/sdk/base/peerconnectiondependencyfactory.cc
* update deps for M83
* Re-enable hevc and openssl build.
This re-enables HEVC and openssl build. Function not verified. Clang build
supported only.
* Fix ffmpeg build issue with msvc
=> Rebase webrtc to M83 (#320)

README.md
Signed-off-by: Geoff Gustafson <geoff@linux.intel.com>
=> Wording changes to clarify README and fix typos

DEPS, scripts/build_android.py, scripts/prepare_dev.py, talk/owt/BUILD.gn, talk/owt/patches/0006-Adjusted-jni_generator.py-to-fit-OWT-code-structure.patch
This enables M83 build on android. Basic functionality verified. No HEVC support but will enable with following PR.
=> Enable android build on M83

talk/owt/sdk/conference/conferenceclient.cc
`ConferenceClient` is removed from signaling channel's observer when `Leave` is called. So it doesn't know when socket.io is disconnected. Therefore, it rejects all `Join` calls after that because its state is always connected.
=> Fix ConferenceClient cannot connect to server twice.

talk/owt/sdk/base/objc/OWTRemoteStream.mm, talk/owt/sdk/base/objc/RemoteStreamObserverObjcImpl.h, talk/owt/sdk/conference/objc/OWTConferenceParticipant.mm, talk/owt/sdk/conference/objc/OWTRemoteMixedStream.mm, talk/owt/sdk/conference/objc/ParticipantObserverObjcImpl.h, talk/owt/sdk/conference/objc/RemoteMixedStreamObserverObjcImpl.h, talk/owt/sdk/include/cpp/owt/base/stream.h, talk/owt/sdk/include/cpp/owt/conference/conferenceclient.h
This change fixes two memory leaks caused by retain cycles.
=> Break retain cycles.

talk/owt/sdk/p2p/objc/OWTP2PClient.m
=> Remove OWTP2PPeerConnectionChannel when it is closed.

talk/owt/sdk/base/win/videorendererwin.cc
=> resolve d3d device lost error

talk/owt/sdk/base/customizedvideoencoderproxy.cc, talk/owt/sdk/base/encodedvideoencoderfactory.cc, talk/owt/sdk/base/functionalobserver.cc, talk/owt/sdk/base/functionalobserver.h, talk/owt/sdk/base/peerconnectionchannel.cc, talk/owt/sdk/base/peerconnectionchannel.h, talk/owt/sdk/conference/conferencepeerconnectionchannel.cc, talk/owt/sdk/include/cpp/owt/p2p/p2pclient.h, talk/owt/sdk/p2p/p2ppeerconnectionchannel.cc, talk/owt/sdk/p2p/p2ppeerconnectionchannel.h
This relands the previous patch for removing pc_thread used in pc channel.
=> PC operation performed synchronously

talk/owt/sdk/conference/conferencepeerconnectionchannel.cc
This is provided as a workaround for specifying codec for conference.  When RtpEncodingParameters can be used for specifying codec, we should switch to that.
=> Only modify local SDP for codec selection

talk/owt/sdk/p2p/p2ppeerconnectionchannel.cc
=> Invoke success callback of send method in event thread.

jenkins/linux.jenkinsfile
=> Add Linux Jenkins file

jenkins/windows.jenkinsfile
=> fix 5.0 jenkinsfile

jenkins/windows.jenkinsfile
=> update windows jenkinsfile

README.md, scripts/build-win.py
Adding a build option in build-win.py for QUIC.
=> Add build options for QUIC

DEPS, scripts/prepare_dev.py, talk/owt/patches/0015-Remove-custom-d8-dependency.patch, talk/owt/patches/0016-Remove-deprecated-create_srcjar-property.patch
This enables m88 android build.
=> Enable M88 android build.

scripts/roll_webrtc.py
refs/heads/owt-bot:roll is incorrect, we need to push changes to refs/heads/roll and create PR from owt-bot:roll.
=> Fix incorrect push target issue.

talk/owt/BUILD.gn, talk/owt/sdk/base/globalconfiguration.cc, talk/owt/sdk/base/win/videorendererd3d11.cc, talk/owt/sdk/base/win/videorendererd3d11.h, talk/owt/sdk/base/win/vpedefs.h, talk/owt/sdk/include/cpp/owt/base/globalconfiguration.h
This commit enables super resolution on Intel platforms, when platform support it.
=> Add super resolution support for renderer.

scripts/build_linux.py, talk/owt/BUILD.gn, talk/owt/sdk/base/linux/msdkvideodecoder.cc, talk/owt/sdk/base/linux/msdkvideodecoder.h, talk/owt/sdk/base/mediautils.cc, talk/owt/sdk/base/mediautils.h, talk/owt/sdk/base/win/mediacapabilities.cc
=> Fix linux build issue after upgrading to M88.

talk/owt/docker/android/Dockerfile
It creates docker image for the libwebrtc part of Android SDK.
=> Add a Dockerfile for Android.

talk/owt/sdk/conference/conferenceclient.cc
Signed-off-by: fanyun <18335108150@163.com>
=> The conference client failed to enter the second room to subscribe stream

talk/owt/sdk/base/customizedframescapturer.cc
This flag was added during rebasing. It looks like this is not needed because Stop() is called in dtor. No task will be invoked after this flag is not alive. As this flag is created in another thread, it also introduces a CHECK failure.
=> Remove PendingTaskSafetyFlag for CustomizedFramesThread.

talk/owt/sdk/base/customizedvideoencoderproxy.cc, talk/owt/sdk/base/desktopcapturer.h, talk/owt/sdk/base/deviceutils.cc, talk/owt/sdk/base/win/video_capture_mf.cc, talk/owt/sdk/base/win/videorendererd3d11.cc
This tries to fix high klocwork issues reported.
=> Fix klocwork issues.

DEPS, README.md, scripts/build-win.py, scripts/build_linux.py, talk/owt/BUILD.gn, talk/owt/sdk/base/win/d3d11va_h264_decoder.cc, talk/owt/sdk/base/win/d3d11va_h264_decoder.h, talk/owt/sdk/base/win/msdkvideodecoderfactory.cc
This change makes it easier for developers to use a specific version of FFmpeg.
=> External ffmpeg support

.github/workflows/ci.yaml, scripts/ci/ci.py
This change enables CI for Linux CG. It's expected to run on GitHub runners.
=> Enable CI for Linux CG.

talk/owt/BUILD.gn, talk/owt/sdk/base/globalconfiguration.cc, talk/owt/sdk/base/peerconnectiondependencyfactory.cc, talk/owt/sdk/base/webrtcvideorendererimpl.cc, talk/owt/sdk/base/win/d3d11_video_decoder.cc, talk/owt/sdk/base/win/externalvideodecoderfactory.cc, talk/owt/sdk/base/win/externalvideodecoderfactory.h, talk/owt/sdk/base/win/ffmpeg_decoder_impl.cc, talk/owt/sdk/base/win/ffmpeg_decoder_impl.h, talk/owt/sdk/include/cpp/owt/base/globalconfiguration.h, talk/owt/sdk/include/cpp/owt/base/videorendererinterface.h
Not able to test this on my side. Submit this for joint debug.
=> Experiment support for decoding into YUV444P by SW FFMPEG decoders.
