open-webrtc-toolkit/owt-client-native

talk/owt/sdk/base/objc/OWTLocalStream.mm
`nativeStream`  has been created in designated initializer by calling `self = [super initWithMediaStream:stream source:sourceInfo];`, so it needn't be created again here.
=> Remove duplicated code

talk/owt/sdk/conference/objc/ConferenceClientObserverObjcImpl.h, talk/owt/sdk/conference/objc/ConferencePublicationObserverObjcImpl.h, talk/owt/sdk/conference/objc/ConferenceSubscriptionObserverObjcImpl.h, talk/owt/sdk/conference/objc/OWTConferenceClient.mm, talk/owt/sdk/conference/objc/OWTConferencePublication.mm, talk/owt/sdk/conference/objc/OWTConferenceSubscription.mm
The retain-cycle looks like this: (-> means retaining)
OWTConferenceClient -> ConferenceClient -> ConferenceSocketSignalingChannel -> OWTConferenceClient
What's the problem? 
Once some one call [client joinWithToken: xxx ], the second lambda (on_failure) which retain self will be retained by ConferenceSocketSignalingChannel finally, but OWTConferenceClient retains the ConferenceSocketSignalingChannel instance, so here is the retain-cycle.
```c++
_nativeConferenceClient->Join(
nativeToken,
[=](std::shared_ptr<owt::conference::ConferenceInfo> info) {
if (onSuccess != nil)
onSuccess([[OWTConferenceInfo alloc]
initWithNativeInfo:info]);
},
// here 👇
[=](std::unique_ptr<owt::base::Exception> e) {
[self triggerOnFailure:onFailure withException:(std::move(e))];
});
```
The retain-cycle looks …
=> Fix retain-cycles

talk/owt/sdk/conference/conferencesocketsignalingchannel.cc, talk/owt/sdk/conference/objc/ConferencePublicationObserverObjcImpl.h, talk/owt/sdk/conference/objc/ConferenceSubscriptionObserverObjcImpl.h, talk/owt/sdk/conference/objc/OWTConferenceClient.mm, talk/owt/sdk/conference/objc/OWTConferencePublication.mm, talk/owt/sdk/conference/objc/OWTConferenceSubscription.mm
1. Instances of ConferenceSubscriptionObserverObjcImpl, ConferencePublicationObserverObjcImpl and ConferenceClientObserverObjcImpl is not deleted in deleter function.
```
- (void)setDelegate:(id<OWTConferenceClientDelegate>)delegate {
if (delegate != nil) {
__weak OWTConferenceClient *weakSelf = self;
_observer = std::unique_ptr<
owt::conference::ConferenceClientObserverObjcImpl,
std::function<void(owt::conference::ConferenceClientObserverObjcImpl*)>>(
new owt::conference::ConferenceClientObserverObjcImpl(self, delegate),
[=](owt::conference::ConferenceClientObserverObjcImpl* observer) {
__strong OWTConferenceClient *strongSelf = weakSelf;
if (strongSelf != nil) {
strongSelf->_nativeConferenceClient->RemoveObserver(*observer);
}
//should delete the observer here 👇
delete observer;
}); …
```
=> Fix memory leak

talk/owt/sdk/base/objc/RemoteStreamObserverObjcImpl.h, talk/owt/sdk/base/objc/RemoteStreamObserverObjcImpl.mm, talk/owt/sdk/base/stream.cc, talk/owt/sdk/conference/conferenceclient.cc, talk/owt/sdk/include/cpp/owt/base/stream.h, talk/owt/sdk/include/cpp/owt/conference/conferenceclient.h, talk/owt/sdk/include/objc/OWT/OWTRemoteStream.h
Even though one didn't subscribe to streams, mute/unmute events can be notified on streams.
=> IOS: Mute Unmute Notifications in Stream

talk/owt/sdk/conference/conferenceclient.cc
I haven't got the point why put the "break; " statement in the bottom of the iteration,  so I think maybe this is a typo, maybe it should be in the bottom of on_failure branch. (the first user in users vector is not current user but the first user entering the room, so does it have any other special meanings here?)
```
auto users = room_info->get_map()["participants"]->get_vector();
// Get current user's ID and trigger |on_success|. Make sure
// |on_success| is triggered before any other events because
// OnUserJoined and OnStreamAdded should be triggered after join a
// conference.
for (auto user_it = users.begin(); user_it != users.end();
user_it++) {
Participant* user_raw;
if (ParseUser(*user_it, &user_raw)) {
std::shared_ptr<Participant> user(user_raw);
const …
```
=> Remove redundant for-loop which adds users to participants_ twice

talk/owt/sdk/base/customizedaudiocapturer.cc, talk/owt/sdk/base/customizedaudiocapturer.h
Even if the thread's priority is set to the highest(kRealtimePriority), there is still a high probability of blocking in actual operation, up to 10 ms, and the blocking time depends on the performance of the mobile devices.
=> fix: error exists in the calculation of need_sleep_ms_ in RecThreadProcess()

talk/owt/sdk/base/peerconnectiondependencyfactory.cc, talk/owt/sdk/base/peerconnectiondependencyfactory.h
The singleton pattern of `PeerConnectionDependencyFactory` was implemented with `std::mutex`. It may have potential deadlock issue.
=> Use std::call_once to create PeerConnectionDependencyFactory.

talk/owt/sdk/base/peerconnectionchannel.cc
If this member is not set, remote side will not associate track to stream.
=> Set transceiver's stream_ids.

talk/owt/sdk/base/peerconnectiondependencyfactory.cc, talk/owt/sdk/base/stream.cc, talk/owt/sdk/include/cpp/owt/base/stream.h
Some features are only available on Windows.
=> Fix undefined symbols error for iOS.

DEPS, talk/owt/BUILD.gn
To unify all HEVC switches, we will use `owt_use_h265` in the future.
Fix #222.
=> Define OWT_USE_H265 when rtc_use_h265 is true.

talk/owt/sdk/base/peerconnectionchannel.cc, talk/owt/sdk/base/peerconnectionchannel.h, talk/owt/sdk/base/peerconnectiondependencyfactory.cc, talk/owt/sdk/include/cpp/owt/p2p/p2pclient.h, talk/owt/sdk/p2p/objc/P2PPeerConnectionChannelObserverObjcImpl.h, talk/owt/sdk/p2p/objc/P2PPeerConnectionChannelObserverObjcImpl.mm, talk/owt/sdk/p2p/p2pclient.cc, talk/owt/sdk/p2p/p2ppeerconnectionchannel.cc, talk/owt/sdk/p2p/p2ppeerconnectionchannel.h, talk/owt/sdk/p2p/p2ppeerconnectionchannelobservercppimpl.cc, talk/owt/sdk/p2p/p2ppeerconnectionchannelobservercppimpl.h
A side effect of this change is memory usage increase because it moves ended channel to a vector instead of dispose them immediately.
This change also add an reference to `pc_factory_ `when it is created. It causes memory leak but fixes hang issue when application exits. AtExitManager might be needed to eventually fix this issue.
=> Fix race conditions during exiting.

talk/owt/sdk/base/functionalobserver.cc, talk/owt/sdk/base/functionalobserver.h, talk/owt/sdk/base/peerconnectionchannel.cc, talk/owt/sdk/base/peerconnectionchannel.h, talk/owt/sdk/conference/conferencepeerconnectionchannel.cc, talk/owt/sdk/p2p/p2ppeerconnectionchannel.cc, talk/owt/sdk/p2p/p2ppeerconnectionchannel.h
`PeerConnection` is thread safe in this version. No need to call it from `pc_thread_`.
=> Remove pc_thread_ from PeerConnectionChannel.

DEPS
This rolls webrtc version from cdef2af8 to 0a571d41.
=> Roll WebRTC version cdef2af8..0a571d41.

DEPS, talk/owt/sdk/base/customizedvideoencoderproxy.cc, talk/owt/sdk/base/globalconfiguration.cc, talk/owt/sdk/base/mediautils.cc, talk/owt/sdk/base/mediautils.h, talk/owt/sdk/base/peerconnectiondependencyfactory.cc, talk/owt/sdk/base/win/msdkvideoencoder.cc, talk/owt/sdk/conference/conferencepeerconnectionchannel.cc, talk/owt/sdk/include/cpp/owt/base/commontypes.h, talk/owt/sdk/include/cpp/owt/base/globalconfiguration.h
Also added a new GlobalConfiguraiton API: SetH264TemporalLayers() to
specify layers requested. Default to 1 and temporal scalability
disabled.
=> Enable temporal scalability for h.264 from MSDK & external encoder.

talk/owt/sdk/base/customizedaudiodevicemodule.cc
Code of customized ADM is mostly from template code in WebRTC. So update the license header to WebRTC's.
=> Update the license header for customized adm impl

talk/owt/sdk/p2p/p2ppeerconnectionchannel.cc, talk/owt/sdk/p2p/p2ppeerconnectionchannel.h
As data channel created is working in ordered, reliable mode, we don't need to wait for acknowledgements from remote side.
Ref: https://github.com/open-webrtc-toolkit/owt-server-p2p/issues/17
=> Fire success callback after writing data to data channel.

scripts/build_linux.py
A new argument is added to allow user fallback to GCC.
=> build_linux.py uses Clang by default.

talk/owt/sdk/base/stream.cc, talk/owt/sdk/include/cpp/owt/base/stream.h
This PR fixes some undefined symbol errors on iOS.
=> Don't compile functions not supported on iOS.

talk/owt/sdk/base/customizedframescapturer.cc, talk/owt/sdk/base/customizedframescapturer.h, talk/owt/sdk/include/cpp/owt/base/framegeneratorinterface.h
method on the FrameGeneratorInterface. Needed for generators that
use thread-senstive resources.
To ensure resources are constructed/destructed on a single thread,
use a bool that is set on the first call to GenerateNextFrame to
construct, and call destructs in the Cleanup() method. Cleanup() has
a default noop implementation for backwards-compatibility.
For [Issue 367](https://github.com/open-webrtc-toolkit/owt-client-native/issues/367)
=> Before exiting the CustomizedFramesThread, call the Cleanup()

scripts/prepare_dev.py, talk/owt/patches/0008-Disable-loop-range-analysis-when-build-with-Xcode-cl.patch
Range loop analysis is disabled by default in clang 12, but it's enabled by clang shipped with Xcode 12. Disable it before warnings in WebRTC are fixed.
=> Disable loop range analysis when build with Xcode clang.

build_overrides/build.gni, talk/owt/BUILD.gn, talk/owt/include/sio_message.h, talk/owt/sdk/base/globalconfiguration.cc, talk/owt/sdk/base/peerconnectionchannel.cc, talk/owt/sdk/base/stream.cc, talk/owt/sdk/conference/conferenceclient.cc, talk/owt/sdk/conference/conferencepeerconnectionchannel.cc, talk/owt/sdk/conference/conferencesocketsignalingchannel.cc, talk/owt/sdk/conference/conferencesocketsignalingchannel.h, talk/owt/sdk/conference/conferencesubscription.cc, talk/owt/sdk/conference/conferencewebtransportchannel.cc, talk/owt/sdk/conference/conferencewebtransportchannel.h, talk/owt/sdk/include/cpp/owt/base/commontypes.h, talk/owt/sdk/include/cpp/owt/base/globalconfiguration.h, talk/owt/sdk/include/cpp/owt/base/localcamerastreamparameters.h, talk/owt/sdk/include/cpp/owt/base/options.h, talk/owt/sdk/include/cpp/owt/base/stream.h, talk/owt/sdk/include/cpp/owt/base/subscription.h, talk/owt/sdk/include/cpp/owt/conference/conferenceclient.h, talk/owt/sdk/include/cpp/owt/conference/conferencepublication.h, talk/owt/sdk/include/cpp/owt/conference/conferencesubscription.h, talk/owt/sdk/include/cpp/owt/conference/streamupdateobserver.h, talk/owt/sdk/include/cpp/owt/conference/subscribeoptions.h
@jianjunz @HuaChunbo PTAL 
this enables the quic transport for MCU that supports it. By default the SDK is not built with quic support. If in gn args owt_use_quic is set to true and owt_quic_header_root is specified, the conference SDK will have quic support.
=> Enable webtransport for native client

talk/owt/sdk/conference/conferenceclient.cc, talk/owt/sdk/conference/conferencepeerconnectionchannel.cc, talk/owt/sdk/include/cpp/owt/base/options.h
v1.2 signaling protocol requires using track_id for subscribing simulcast stream. Each remote stream will have a single stream id but multiple track_id, one for each simulcast ssrc.
=> Use track id for simulcast stream subscription.

scripts/roll_webrtc.py
This PR adds a script to roll owt-deps-webrtc revision in DEPS, and create a git commit locally. A new GitHub Actions workflow will be added to owt-deps-webrtc repo to run this script when a new commit is pushed to the main branch.
=> Add an auto roller for owt-deps-webrtc.

talk/owt/BUILD.gn, talk/owt/sdk/base/win/d3d11_manager.h, talk/owt/sdk/base/win/device_info_mf.cc, talk/owt/sdk/base/win/device_info_mf.h, talk/owt/sdk/base/win/video_capture_mf.cc, talk/owt/sdk/base/win/video_capture_mf.h
This pr implements media foundation based video capturerer as the preparing for zero-buffer copy between encoder and capturer on windows.
LocalStream creation with this new capturerer is not implemented, and will be enabled together with updated hardware encoder.
Media foundation based video capture require Win8 and Win10 to work.
=> Implement media foundation based video capturer.

scripts/build-win.py, talk/owt/BUILD.gn
Enable Windows on arm64 compile target support using the VC cross compile toolchain, some modifications to build_win.py and owt\talk\BUILD.gn to support compilation
=> Build script enable windows arm64 target

talk/owt/sdk/conference/conferencewebtransportchannel.cc
Fix for null terminator when copying the certificate fingerprint string, when setting the fingerprint manually.
fixes #540
=> Allocate and copy null terminator when copying fingerprint string

README.md, README.webtransport, talk/owt/BUILD.gn, talk/owt/docs/cpp/cpp.md, talk/owt/sdk/base/stream.cc, talk/owt/sdk/conference/conferenceclient.cc, talk/owt/sdk/conference/conferencesubscription.cc, talk/owt/sdk/conference/conferencewebtransportchannel.cc, talk/owt/sdk/conference/conferencewebtransportchannel.h, talk/owt/sdk/include/cpp/owt/base/stream.h, talk/owt/sdk/include/cpp/owt/base/subscription.h, talk/owt/sdk/include/cpp/owt/conference/conferenceclient.h, talk/owt/sdk/include/cpp/owt/conference/conferencesubscription.h, talk/owt/sdk/include/cpp/owt/conference/streamupdateobserver.h
Switch from quictransport to webtransport to accommodate to server's switch.
=> Switch from QuicTransport to WebTransport for conference SDK.

talk/owt/BUILD.gn, talk/owt/sdk/base/peerconnectiondependencyfactory.cc
Add default linking for Windows SDK, to avoid application missing linker input when building.
=> Add default linking for VS build.

scripts/build-win.py
Cross compiling support in webrtc is only supported using llvm/clang, and by default uses a version of clang that is prebuilt by google. This version also enables libc++ (clang) experimental features (from c++11) in nested namespaces, which can conflict with other binaries built with the system clang tool/toolchain using msvc++ libraries. Disabling the experimental features, and disabling using the custom llvm/clang allows client libraries compiled on the same win system using the msvcpp toolchain
=> Ensure llvm builds don't use libc++

talk/owt/sdk/include/cpp/owt/p2p/p2pclient.h, talk/owt/sdk/p2p/p2pclient.cc, talk/owt/sdk/p2p/p2ppeerconnectionchannel.cc
Some raw pointers are not freed.
=> Fix some memory leaks.

talk/owt/BUILD.gn, talk/owt/sdk/base/codecutils.cc, talk/owt/sdk/base/codecutils.h, talk/owt/sdk/base/customizedvideodecoderfactory.cc, talk/owt/sdk/base/customizedvideoencoderproxy.cc, talk/owt/sdk/base/encodedvideoencoderfactory.cc, talk/owt/sdk/base/linux/msdkvideodecoderfactory.cc, talk/owt/sdk/base/mediautils.h, talk/owt/sdk/base/objc/OWTDefaultVideoDecoderFactory.m, talk/owt/sdk/base/objc/OWTDefaultVideoEncoderFactory.m, talk/owt/sdk/base/objc/OWTLocalStream.mm, talk/owt/sdk/base/peerconnectiondependencyfactory.cc, talk/owt/sdk/base/peerconnectiondependencyfactory.h, talk/owt/sdk/base/stream.cc, talk/owt/sdk/base/win/mediacapabilities.cc, talk/owt/sdk/base/win/msdkvideodecoder.cc, talk/owt/sdk/base/win/msdkvideodecoderfactory.cc, talk/owt/sdk/base/win/msdkvideoencoder.cc, talk/owt/sdk/base/win/msdkvideoencoderfactory.cc, talk/owt/sdk/include/cpp/owt/base/stream.h, talk/owt/sdk/p2p/p2ppeerconnectionchannel.cc, talk/owt/sdk/p2p/tests/BUILD.gn, talk/owt/sdk/p2p/tests/e2e_tests.cc
This change enables HEVC support after rebasing to M108. HEVC related structures are always declared, but the codec is only implemented when GN arg rtc_use_h265 is enabled (macro WEBRTC_USE_H265 is defined).
=> Add HEVC support.

talk/owt/sdk/base/mediautils.cc, talk/owt/sdk/base/win/msdkvideoencoder.cc
Also added a new GlobalConfiguraiton API: SetH264TemporalLayers() to specify layers requested. Default to 1 and temporal scalability disabled.
=> Pick "Enable temporal scalability for h.264 from MSDK & external encoder."

scripts/prepare_dev.py, talk/owt/patches/0019-Enable-C-20-on-iOS.patch, talk/owt/patches/0020-Enable-C-20-for-all-platforms-but-LaCrOS-and-Fuchsia.patch, talk/owt/patches/0021-Allow-third-party-repositories-to-disable-C-20-for-M.patch
Some code requires C++20 features, like designated initializers. When build with MSVC, `/std:c++20` should be specified explicitly for some targets.
=> Enable C++20.

talk/owt/BUILD.gn, talk/owt/sdk/base/customizedaudiodevicemodule.cc, talk/owt/sdk/base/customizedoutputaudiodevicemodule.cc, talk/owt/sdk/base/customizedoutputaudiodevicemodule.h
This allows audio data received to be routed to implementations of AudioPlayerInterface without depending on platform audio module.
=> Add CustomizedOutputAudioDeviceModule.

scripts/build-win.py
<stdatomic.h> shipped with VS2022 is not yet supported when compiling as C.
=> Use ffmpeg's stdatomic fallback on Windows.

scripts/build-win.py, scripts/build_linux.py, talk/owt/BUILD.gn
This change also removes some configuration for SSL, which is moved to rtc_base by https://github.com/open-webrtc-toolkit/owt-deps-webrtc/pull/190.
=> Socket.IO is not needed when building for cloud gaming.

talk/owt/BUILD.gn
libowt.a is expected to be a complete static lib.
=> Disable thin archive for OWT SDK static lib on Linux.

talk/owt/sdk/p2p/p2pclient.cc
When local endpoint is a caller, chat-ua is received after the PeerConnection is created.
=> Don't close PeerConnection when chat-ua is received.

DEPS, build_overrides/build.gni, scripts/build-win.py, scripts/build_linux.py, talk/owt/BUILD.gn
This changes allows third_party/webrtc access owt_ffmpeg_root as well. So external headers will be included when it's defined.
=> Define GN arg owt_ffmpeg_root for the whole project.

talk/owt/BUILD.gn, talk/owt/sdk/base/linux/msdkvideodecoderfactory.cc, talk/owt/sdk/base/linux/msdkvideodecoderfactory.h, talk/owt/sdk/base/peerconnectiondependencyfactory.cc, talk/owt/sdk/base/win/d3d11va_h264_decoder.cc, talk/owt/sdk/base/win/externalvideodecoderfactory.cc, talk/owt/sdk/base/win/externalvideodecoderfactory.h, talk/owt/sdk/base/win/externalvideoencoderfactory.cc, talk/owt/sdk/base/win/externalvideoencoderfactory.h
This change enables external video decoder factory for both MSDK decoder and FFMPEG decoder.
=> Support hardware accelerated FFMPEG decoder.

talk/owt/BUILD.gn, talk/owt/sdk/base/peerconnectiondependencyfactory.cc
This is a workaround for CG build. As CG server always uses encoded video input, WebRTC cannot select codecs based on negotiation. It is assumed CG apps take care of actual codecs.
=> CG build claims to support all codecs.

talk/owt/sdk/base/logging.cc
We initialized the stream to write to in LogToFileRotate() but it got deinitialized on the exit from the scope while its reference remained in the logging which causes a crash on the first write. That's a quick fix. More appropriately would be to change webrtc function prototype for it to accept stream for the ref count increment.
=> logging: use static stream in LogToFileRotate

talk/owt/sdk/base/sdputils.cc
m=section could be rejected because of no match codecs. In this case, munging SDP here may result media format description to be empty.
=> Ignore rejected m= sections

talk/owt/sdk/base/customizedvideoencoderproxy.cc, talk/owt/sdk/base/win/d3d11_video_decoder.cc, talk/owt/sdk/base/win/d3d11_video_decoder.h
The implementation is picked from MSDK video decoder.
=> D3D11 decoder supports getting side data from HEVC streams.

talk/owt/sdk/base/logging.cc, talk/owt/sdk/include/cpp/owt/base/logging.h
This is to work with https://github.com/open-webrtc-toolkit/owt-deps-webrtc/pull/202 to support rotating log to file with prefix specified by application.
=> Add OWT API to support rotating log to file with specified prefix.

talk/owt/sdk/base/customizedaudiocapturer.cc
Capturer caculates the time of next GenerateFramesForNext10Ms based on these counters. If they are not reset when stop recording, new session will send out too much data in the begining.
=> Reset counters when stop recording.

scripts/prepare_dev.py, talk/owt/patches/0010-Roll-clang-llvmorg-18-init-12938-geb1d5065.patch, talk/owt/patches/0011-Suppress-some-warnings-for-clang-18.patch
=> Roll clang llvmorg-18-init-12938-geb1d5065.
